/*
Mouner Dabjan
October 14 2018 
Multiple Choice Quiz
 */

/**
 *
 * @author canada
 */
public class Quiz extends javax.swing.JFrame {

    /**
     * Creates new form Quiz
     */
    public Quiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleee = new javax.swing.JLabel();
        correctanswer = new javax.swing.JLabel();
        incorrectanswer = new javax.swing.JLabel();
        percentageofcorrect = new javax.swing.JLabel();
        startvalue1 = new javax.swing.JLabel();
        startvalue2 = new javax.swing.JLabel();
        startvalue3 = new javax.swing.JLabel();
        submitbutton = new javax.swing.JButton();
        question1 = new javax.swing.JLabel();
        question2 = new javax.swing.JLabel();
        question3 = new javax.swing.JLabel();
        question4 = new javax.swing.JLabel();
        question5 = new javax.swing.JLabel();
        question6 = new javax.swing.JLabel();
        txtfield1 = new javax.swing.JTextField();
        txtfield2 = new javax.swing.JTextField();
        txtfield3 = new javax.swing.JTextField();
        txtfield4 = new javax.swing.JTextField();
        txtfield5 = new javax.swing.JTextField();
        txtfield6 = new javax.swing.JTextField();
        instructions = new javax.swing.JLabel();
        question1I = new javax.swing.JLabel();
        question1II = new javax.swing.JLabel();
        question1III = new javax.swing.JLabel();
        question2I = new javax.swing.JLabel();
        question2II = new javax.swing.JLabel();
        question2III = new javax.swing.JLabel();
        question3I = new javax.swing.JLabel();
        question3II = new javax.swing.JLabel();
        question3III = new javax.swing.JLabel();
        question4I = new javax.swing.JLabel();
        question4II = new javax.swing.JLabel();
        question4III = new javax.swing.JLabel();
        question4IV = new javax.swing.JLabel();
        question5I = new javax.swing.JLabel();
        question5II = new javax.swing.JLabel();
        question5III = new javax.swing.JLabel();
        question5IV = new javax.swing.JLabel();
        question5V = new javax.swing.JLabel();
        question5VI = new javax.swing.JLabel();
        question6I = new javax.swing.JLabel();
        question6II = new javax.swing.JLabel();
        question6III = new javax.swing.JLabel();
        question6IV = new javax.swing.JLabel();
        question6V = new javax.swing.JLabel();
        exp1 = new javax.swing.JLabel();
        exp2 = new javax.swing.JLabel();
        exp3 = new javax.swing.JLabel();
        exp4 = new javax.swing.JLabel();
        exp5 = new javax.swing.JLabel();
        exp6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        titleee.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titleee.setText("Multiple Choice Quiz");

        correctanswer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        correctanswer.setText("Number of questions answered correctly: ");

        incorrectanswer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        incorrectanswer.setText("Number of questions answered incorrectly: ");

        percentageofcorrect.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        percentageofcorrect.setText("Percentage of correct answers: ");

        startvalue1.setText("0");

        startvalue2.setText("0");

        startvalue3.setText("0");

        submitbutton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        submitbutton.setText("Submit Quiz");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        question1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question1.setText("1. int val1 = 2 ;");

        question2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question2.setText("2. int num1 = 6;");

        question3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question3.setText("3. int num1 = 20; ");

        question4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question4.setText("4. int val1 = 2;");

        question5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question5.setText("5. int number1 = 10;");

        question6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question6.setText("6. int val1 = 20;");

        instructions.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        instructions.setText("Read the following code and write down the value of the answer ");

        question1I.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question1I.setText("int val2 = 4;");

        question1II.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question1II.setText("int val3;");

        question1III.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question1III.setText("val3 = val2 + val3");

        question2I.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question2I.setText("int num2 = 8;");

        question2II.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question2II.setText("int num3;");

        question2III.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question2III.setText("num3 = num2 - num6;");

        question3I.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question3I.setText("int num2 = 4;");

        question3II.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question3II.setText("int num3;");

        question3III.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question3III.setText("num3 = num1 / num2; ");

        question4I.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question4I.setText("int val2 = 4;");

        question4II.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question4II.setText("int val3 = 3;");

        question4III.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question4III.setText("int val4;");

        question4IV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question4IV.setText("val4 = val3 * val2 * val1;");

        question5I.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question5I.setText(" int number2 = number1 * 5;");

        question5II.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question5II.setText("int number3 = number1 + number2;");

        question5III.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question5III.setText("if (number3 < number1)");

        question5IV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question5IV.setText("{System.out.println(\"7\");}");
        question5IV.setToolTipText("");

        question5V.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question5V.setText(" else");

        question5VI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question5VI.setText("{System.out.println(\"6\");}");

        question6I.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question6I.setText("  int val2 = val1 + 40;");

        question6II.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question6II.setText("  if (val1 > 20)");

        question6III.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question6III.setText("{val1 = val2 + 10;}");

        question6IV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question6IV.setText("    else");

        question6V.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        question6V.setText("{val2 = val2 - 10;}");

        exp1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        exp2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        exp3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        exp4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        exp5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        exp6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(incorrectanswer)
                            .addComponent(correctanswer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startvalue2)
                            .addComponent(startvalue1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtfield3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211)
                        .addComponent(submitbutton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(instructions))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exp1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exp3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(percentageofcorrect)
                        .addGap(18, 18, 18)
                        .addComponent(startvalue3)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(question1I)
                                    .addComponent(question1III)
                                    .addComponent(question1II))))
                        .addGap(309, 309, 309)
                        .addComponent(exp4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(titleee))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exp5, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(question2II)
                                    .addComponent(question2I)
                                    .addComponent(question2III)
                                    .addComponent(txtfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(question4I)
                                        .addComponent(question4)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(question4III)
                                            .addGap(24, 24, 24))
                                        .addComponent(question4II))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(question4IV))
                                    .addComponent(txtfield4, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(question6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(question6I)
                                            .addComponent(question6II)
                                            .addComponent(question6III)
                                            .addComponent(question6IV)
                                            .addComponent(question6V)))
                                    .addComponent(exp2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(exp6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtfield6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question3)
                            .addComponent(txtfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(question5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(question3II)
                                    .addComponent(question3I)
                                    .addComponent(question3III)
                                    .addComponent(question5II)
                                    .addComponent(question5I)
                                    .addComponent(txtfield5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(question5III)
                                    .addComponent(question5IV)
                                    .addComponent(question5V)
                                    .addComponent(question5VI))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(titleee)
                .addGap(18, 18, 18)
                .addComponent(instructions)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(question1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(question1I)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(question1II)
                        .addGap(6, 6, 6)
                        .addComponent(question1III)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(question2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(question2I)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(question2II)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(question2III)
                        .addGap(16, 16, 16)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(txtfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(exp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exp2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question3, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(question4))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question3I)
                    .addComponent(question4I))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(question3II))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(question4II)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(question3III)
                    .addComponent(question4III))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(question4IV)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfield4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(exp3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exp4, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question5)
                            .addComponent(question6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question5I)
                            .addComponent(question6I))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(question5II)
                            .addComponent(question6II))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(question5III)
                            .addComponent(question6III))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(question5IV)
                            .addComponent(question6IV))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(question5V)
                            .addComponent(question6V))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(question5VI)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfield6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfield5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(exp6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(exp5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correctanswer)
                    .addComponent(startvalue1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitbutton)
                    .addComponent(incorrectanswer)
                    .addComponent(startvalue2))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentageofcorrect)
                    .addComponent(startvalue3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed

        // constants 
        
       final int COR_1 = 6;  
       final int COR_2 = 2;
       final int COR_3 = 5; 
       final int COR_4 = 24; 
       final int COR_6 = 50; 
       final int COR_5 = 6;
       
      
       // variables 
       
       int coranswer= 0;
       int incanswer = 0;
       double percorrect = 0; 
       int userguess1;
       int userguess2;
       int userguess3;
       int userguess4;
       int userguess5;
       int userguess6; 
       
       
       // getting user input
       
       userguess1 = Integer.parseInt(txtfield1.getText()); 
       userguess2 = Integer.parseInt(txtfield2.getText());
       userguess3 = Integer.parseInt(txtfield3.getText()); 
       userguess4 = Integer.parseInt(txtfield4.getText());
       userguess5 = Integer.parseInt(txtfield5.getText());
       userguess6 = Integer.parseInt(txtfield6.getText()); 
       
       
       // if-statements 
       
       
       if (userguess1 == COR_1)
       {
           exp1.setText("Your answer is Correct!"); 
           coranswer = coranswer + 1; 
       }
       else
       {
           exp1.setText("Your answer is Incorrect"); 
           incanswer = incanswer + 1; 
       }
       
       
       
       if (userguess2 == COR_2)
       {
           exp2.setText("Your answer is Correct!");
           coranswer = coranswer + 1;
       }
       else
       {
           exp2.setText("Your answer is Incorrect");
           incanswer = incanswer + 1; 
       }
       
       
       if (userguess3 == COR_3)
       {
           exp3.setText("Your answer is Correct!");
           coranswer = coranswer + 1;
       }
       else
       {
           exp3.setText("Your answer is Incorrect");
           incanswer = incanswer + 1; 
           
       }
       
       if (userguess4 == COR_4)
       {
           exp4.setText("Your answer is Correct!");
           coranswer = coranswer + 1;
       }
       else
       {
           exp4.setText("Your answer is Incorrect");
           incanswer = incanswer + 1; 
       }
       
       if (userguess5 == COR_5)
       {
           exp5.setText("Your answer is Correct!");
           coranswer = coranswer + 1;
       }
       else
       {
           exp5.setText("Your answer is Incorrect");
           incanswer = incanswer + 1; 
       }
       
       if (userguess6 == COR_6)
       {
           exp6.setText("Your answer is Correct!");
           coranswer = coranswer + 1;
       }
       else
       {
           exp6.setText("Your answer is Incorrect");
           incanswer = incanswer + 1;
       }
       
       
       // output 
       
       percorrect = ((double)coranswer/(double)incanswer) *100; 
       percorrect = percorrect * 100;
       percorrect = Math.round(percorrect);
       percorrect = percorrect / 100; 
       
       startvalue1.setText(String.valueOf(coranswer));
       startvalue2.setText(String.valueOf(incanswer));
       startvalue3.setText(String.valueOf(percorrect)); 
       
       
       
       
       
      
               
               
            
   
        
       
    
        
    }//GEN-LAST:event_submitbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel correctanswer;
    private javax.swing.JLabel exp1;
    private javax.swing.JLabel exp2;
    private javax.swing.JLabel exp3;
    private javax.swing.JLabel exp4;
    private javax.swing.JLabel exp5;
    private javax.swing.JLabel exp6;
    private javax.swing.JLabel incorrectanswer;
    private javax.swing.JLabel instructions;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel percentageofcorrect;
    private javax.swing.JLabel question1;
    private javax.swing.JLabel question1I;
    private javax.swing.JLabel question1II;
    private javax.swing.JLabel question1III;
    private javax.swing.JLabel question2;
    private javax.swing.JLabel question2I;
    private javax.swing.JLabel question2II;
    private javax.swing.JLabel question2III;
    private javax.swing.JLabel question3;
    private javax.swing.JLabel question3I;
    private javax.swing.JLabel question3II;
    private javax.swing.JLabel question3III;
    private javax.swing.JLabel question4;
    private javax.swing.JLabel question4I;
    private javax.swing.JLabel question4II;
    private javax.swing.JLabel question4III;
    private javax.swing.JLabel question4IV;
    private javax.swing.JLabel question5;
    private javax.swing.JLabel question5I;
    private javax.swing.JLabel question5II;
    private javax.swing.JLabel question5III;
    private javax.swing.JLabel question5IV;
    private javax.swing.JLabel question5V;
    private javax.swing.JLabel question5VI;
    private javax.swing.JLabel question6;
    private javax.swing.JLabel question6I;
    private javax.swing.JLabel question6II;
    private javax.swing.JLabel question6III;
    private javax.swing.JLabel question6IV;
    private javax.swing.JLabel question6V;
    private javax.swing.JLabel startvalue1;
    private javax.swing.JLabel startvalue2;
    private javax.swing.JLabel startvalue3;
    private javax.swing.JButton submitbutton;
    private javax.swing.JLabel titleee;
    private javax.swing.JTextField txtfield1;
    private javax.swing.JTextField txtfield2;
    private javax.swing.JTextField txtfield3;
    private javax.swing.JTextField txtfield4;
    private javax.swing.JTextField txtfield5;
    private javax.swing.JTextField txtfield6;
    // End of variables declaration//GEN-END:variables
}
